CREATE DATABASE survey;

CREATE TABLE survey_results_2024 (
    ResponseId INT,
    MainBranch TEXT,
    Age TEXT,
    Employment TEXT,
    RemoteWork TEXT,
    `Check` TEXT,
    CodingActivities TEXT,
    EdLevel TEXT,
    LearnCode TEXT,
    LearnCodeOnline TEXT,
    TechDoc TEXT,
    YearsCode TEXT,
    YearsCodePro TEXT,
    DevType TEXT,
    OrgSize TEXT,
    PurchaseInfluence TEXT,
    BuyNewTool TEXT,
    BuildvsBuy TEXT,
    TechEndorse TEXT,
    Country TEXT,
    Currency TEXT,
    CompTotal TEXT,
    LanguageHaveWorkedWith TEXT,
    LanguageWantToWorkWith TEXT,
    LanguageAdmired TEXT,
    DatabaseHaveWorkedWith TEXT,
    DatabaseWantToWorkWith TEXT,
    DatabaseAdmired TEXT,
    PlatformHaveWorkedWith TEXT,
    PlatformWantToWorkWith TEXT,
    PlatformAdmired TEXT,
    WebframeHaveWorkedWith TEXT,
    WebframeWantToWorkWith TEXT,
    WebframeAdmired TEXT,
    EmbeddedHaveWorkedWith TEXT,
    EmbeddedWantToWorkWith TEXT,
    EmbeddedAdmired TEXT,
    MiscTechHaveWorkedWith TEXT,
    MiscTechWantToWorkWith TEXT,
    MiscTechAdmired TEXT,
    ToolsTechHaveWorkedWith TEXT,
    ToolsTechWantToWorkWith TEXT,
    ToolsTechAdmired TEXT,
    NEWCollabToolsHaveWorkedWith TEXT,
    NEWCollabToolsWantToWorkWith TEXT,
    NEWCollabToolsAdmired TEXT,
    `OpSysPersonal use` TEXT,
    `OpSysProfessional use` TEXT,
    OfficeStackAsyncHaveWorkedWith TEXT,
    OfficeStackAsyncWantToWorkWith TEXT,
    OfficeStackAsyncAdmired TEXT,
    OfficeStackSyncHaveWorkedWith TEXT,
    OfficeStackSyncWantToWorkWith TEXT,
    OfficeStackSyncAdmired TEXT,
    AISearchDevHaveWorkedWith TEXT,
    AISearchDevWantToWorkWith TEXT,
    AISearchDevAdmired TEXT,
    NEWSOSites TEXT,
    SOVisitFreq TEXT,
    SOAccount TEXT,
    SOPartFreq TEXT,
    SOHow TEXT,
    SOComm TEXT,
    AISelect TEXT,
    AISent TEXT,
    AIBen TEXT,
    AIAcc TEXT,
    AIComplex TEXT,
    `AIToolCurrently Using` TEXT,
    `AIToolInterested in Using` TEXT,
    `AIToolNot interested in Using` TEXT,
    `AINextMuch more integrated` TEXT,
    AINextNoChange TEXT,
    AINextMoreIntegrated TEXT,
    AINextLessIntegrated TEXT,
    AINextMuchLessIntegrated TEXT,
    AIThreat TEXT,
    AIEthics TEXT,
    AIChallenges TEXT,
    TBranch TEXT,
    ICorPM TEXT,
    WorkExp TEXT,
    Knowledge_1 TEXT,
    Knowledge_2 TEXT,
    Knowledge_3 TEXT,
    Knowledge_4 TEXT,
    Knowledge_5 TEXT,
    Knowledge_6 TEXT,
    Knowledge_7 TEXT,
    Knowledge_8 TEXT,
    Knowledge_9 TEXT,
    Frequency_1 TEXT,
    Frequency_2 TEXT,
    Frequency_3 TEXT,
    TimeSearching TEXT,
    TimeAnswering TEXT,
    Frustration TEXT,
    ProfessionalTech TEXT,
    ProfessionalCloud TEXT,
    ProfessionalQuestion TEXT,
    Industry TEXT,
    JobSatPoints_1 TEXT,
    JobSatPoints_4 TEXT,
    JobSatPoints_5 TEXT,
    JobSatPoints_6 TEXT,
    JobSatPoints_7 TEXT,
    JobSatPoints_8 TEXT,
    JobSatPoints_9 TEXT,
    JobSatPoints_10 TEXT,
    JobSatPoints_11 TEXT,
    SurveyLength TEXT,
    SurveyEase TEXT,
    ConvertedCompYearly TEXT,
    JobSat TEXT
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/survey_results_public.csv'
INTO TABLE survey_results_2024
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;
